import { NAME } from './constants';

export const REQUEST_ALL_MATCHES_DATA = `${NAME}/REQUEST_ALL_MATCHES_DATA`;
export const REQUEST_ALL_MATCHES_SUCCESS = `${NAME}/REQUEST_ALL_MATCHES_SUCCESS`;
export const REQUEST_ALL_MATCHES_FAILURE = `${NAME}/REQUEST_ALL_MATCHES_FAILURE`;


