import { NAME } from './constants';

export const SET_REIMPORT_MODE = `${NAME}/SET_REIMPORT_MODE`;

export const REQUEST_SHOW_ALERT = `${NAME}/REQUEST_SHOW_ALERT`;
export const REQUEST_SHOW_ALERT_SUCCESS = `${NAME}/REQUEST_SHOW_ALERT_SUCCESS`;
export const REQUEST_SHOW_ALERT_FAILURE = `${NAME}/REQUEST_SHOW_ALERT_FAILURE`;


export const REQUEST_MATCH_DATA = `${NAME}/REQUEST_MATCH_DATA`;
export const REQUEST_MATCH_DATA_SUCCESS = `${NAME}/REQUEST_MATCH_DATA_SUCCESS`;
export const REQUEST_MATCH_DATA_FAILURE = `${NAME}/REQUEST_MATCH_DATA_FAILURE`;


